name: Main

on:
  push:
  pull_request:

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} (${{ matrix.os }}-latest)
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, macos ]
        ruby: [ '2.7', '3.2' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Update rubygems (Get the newest version to rid ourselves of warnings)
        run: gem update --system --no-document

      - name: Install bundler
        run: gem i bundler --no-document

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake test

      - name: Run linter
        run: bundle exec rake rubocop
